use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};

static NEXT_FIXTURE_ID: AtomicU64 = AtomicU64::new(0);

fn temp_root() -> PathBuf {
    let sequence = NEXT_FIXTURE_ID.fetch_add(1, Ordering::Relaxed);
    let root = std::env::temp_dir().join(format!(
        "codedb-relative-frontdoor-{}-{sequence}",
        std::process::id()
    ));
    fs::create_dir(&root).expect("reserve unique integration-test root");
    root
}

#[test]
fn scan_and_export_accept_nontrivial_relative_repo_paths() {
    let root = temp_root();
    let fixture = root.join("fixture");
    fs::create_dir_all(fixture.join("src")).expect("create fixture source");
    fs::create_dir(root.join("nested")).expect("create invocation directory");
    fs::write(
        fixture.join("Cargo.toml"),
        "[package]\nname = \"relative_fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write fixture manifest");
    fs::write(
        fixture.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"relative_fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write locked fixture context");
    fs::write(fixture.join("src/lib.rs"), "pub fn relative() {}\n").expect("write fixture source");

    let relative_repo = "../fixture";
    for args in [
        vec!["scan", relative_repo, "--format", "json"],
        vec![
            "export",
            "cargo_packages",
            "--repo-path",
            relative_repo,
            "--format",
            "json",
        ],
    ] {
        let output = Command::new(env!("CARGO_BIN_EXE_codedb"))
            .current_dir(root.join("nested"))
            .args(&args)
            .output()
            .expect("run packaged CodeDB binary");
        assert!(
            output.status.success(),
            "relative frontdoor failed for {args:?}: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let rows: serde_json::Value =
            serde_json::from_slice(&output.stdout).expect("parse CodeDB JSON rows");
        assert!(
            rows.as_array().is_some_and(|rows| rows.iter().any(|row| {
                row.get("table").and_then(serde_json::Value::as_str) == Some("cargo_packages")
            })),
            "relative frontdoor omitted Cargo package evidence for {args:?}: {rows}"
        );
    }

    fs::remove_dir_all(root).expect("remove integration-test root");
}
