use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use sha2::{Digest, Sha256};
use std::sync::atomic::{AtomicU64, Ordering};

static NEXT_FIXTURE_ID: AtomicU64 = AtomicU64::new(0);

fn temp_root() -> PathBuf {
    let sequence = NEXT_FIXTURE_ID.fetch_add(1, Ordering::Relaxed);
    let root = std::env::temp_dir().join(format!(
        "codedb-relative-frontdoor-{}-{sequence}",
        std::process::id()
    ));
    fs::create_dir(&root).expect("reserve unique integration-test root");
    root
}

#[test]
fn scan_and_export_accept_nontrivial_relative_repo_paths() {
    let root = temp_root();
    let fixture = root.join("fixture");
    fs::create_dir_all(fixture.join("src")).expect("create fixture source");
    fs::create_dir(root.join("nested")).expect("create invocation directory");
    fs::write(
        fixture.join("Cargo.toml"),
        "[package]\nname = \"relative_fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write fixture manifest");
    fs::write(
        fixture.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"relative_fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write locked fixture context");
    fs::write(fixture.join("src/lib.rs"), "pub fn relative() {}\n").expect("write fixture source");

    let relative_repo = "../fixture";
    for args in [
        vec!["scan", relative_repo, "--format", "json"],
        vec![
            "export",
            "cargo_packages",
            "--repo-path",
            relative_repo,
            "--format",
            "json",
        ],
    ] {
        let output = Command::new(env!("CARGO_BIN_EXE_codedb"))
            .current_dir(root.join("nested"))
            .args(&args)
            .output()
            .expect("run packaged CodeDB binary");
        assert!(
            output.status.success(),
            "relative frontdoor failed for {args:?}: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let rows: serde_json::Value =
            serde_json::from_slice(&output.stdout).expect("parse CodeDB JSON rows");
        assert!(
            rows.as_array().is_some_and(|rows| rows.iter().any(|row| {
                row.get("table").and_then(serde_json::Value::as_str) == Some("cargo_packages")
            })),
            "relative frontdoor omitted Cargo package evidence for {args:?}: {rows}"
        );
    }

    fs::remove_dir_all(root).expect("remove integration-test root");
}

#[test]
fn generated_yazelix_bridge_has_provenance_checksums_and_leaves_config_untouched() {
    let root = temp_root();
    let out_dir = root.join("generated");
    let tracked_config = root.join("config.nu");
    let config_contents = "# tracked Yazelix configuration\n$env.KEEP_ME = 'yes'\n";
    fs::write(&tracked_config, config_contents).expect("write tracked config fixture");

    let output = Command::new(env!("CARGO_BIN_EXE_codedb"))
        .args(["generate-yazelix-bridge", "--out-dir"])
        .arg(&out_dir)
        .args(["--format", "json"])
        .output()
        .expect("generate Yazelix bridge");
    assert!(
        output.status.success(),
        "bridge generation failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let rows: Vec<BTreeMap<String, String>> =
        serde_json::from_slice(&output.stdout).expect("parse bridge artifact rows");
    assert_eq!(
        rows.len(),
        3,
        "generator reports both Nu artifacts and manifest"
    );
    for artifact in ["codedb_init", "codedb_extern", "codedb_bridge_manifest"] {
        let row = rows
            .iter()
            .find(|row| row.get("artifact").is_some_and(|value| value == artifact))
            .unwrap_or_else(|| panic!("missing {artifact} artifact row: {rows:?}"));
        assert_eq!(row.get("generated").map(String::as_str), Some("true"));
        assert_eq!(
            row.get("manual_edits_allowed").map(String::as_str),
            Some("false")
        );
        assert_eq!(
            row.get("mutates_plugin_registry").map(String::as_str),
            Some("false")
        );
        assert!(
            row.get("sha256")
                .is_some_and(|checksum| checksum.len() == 64),
            "artifact row must include a SHA-256 checksum: {row:?}"
        );
    }

    let manifest: serde_json::Value = serde_json::from_slice(
        &fs::read(out_dir.join("codedb_bridge_manifest.json")).expect("read bridge manifest"),
    )
    .expect("parse bridge manifest");
    assert_eq!(
        manifest["generator"],
        serde_json::Value::String("codedb generate-yazelix-bridge".to_string())
    );
    assert_eq!(manifest["artifacts"].as_array().map(Vec::len), Some(2));
    assert_eq!(
        manifest["source_templates"],
        serde_json::json!([
            "templates/nushell/codedb_init.nu",
            "templates/nushell/codedb_extern.nu",
        ])
    );
    for (artifact, filename) in [
        ("codedb_init", "codedb_init.nu"),
        ("codedb_extern", "codedb_extern.nu"),
    ] {
        let expected_checksum = format!(
            "{:x}",
            Sha256::digest(fs::read(out_dir.join(filename)).expect("read generated artifact"))
        );
        let row = rows
            .iter()
            .find(|row| row.get("artifact").is_some_and(|value| value == artifact))
            .expect("generated artifact row exists");
        assert_eq!(row.get("sha256"), Some(&expected_checksum));
        let manifest_artifact = manifest["artifacts"]
            .as_array()
            .expect("manifest artifact array")
            .iter()
            .find(|entry| entry["artifact"] == artifact)
            .expect("manifest artifact exists");
        assert_eq!(manifest_artifact["sha256"], expected_checksum);
        assert_eq!(manifest_artifact["mutates_plugin_registry"], false);
    }
    assert_eq!(
        fs::read_to_string(&tracked_config).expect("read tracked config fixture"),
        config_contents,
        "bridge generation must not edit tracked config.nu"
    );
    assert!(
        !out_dir.join("config.nu").exists(),
        "bridge generation writes only bridge artifacts"
    );

    fs::remove_dir_all(root).expect("remove integration-test root");
}

#[test]
fn envctl_export_binds_materialization_rows_to_exported_table_checksums() {
    let root = temp_root();
    let fixture = root.join("fixture");
    fs::create_dir_all(fixture.join("src")).expect("create fixture source");
    fs::write(
        fixture.join("Cargo.toml"),
        "[package]\nname = \"envctl_fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write fixture manifest");
    fs::write(
        fixture.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"envctl_fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write locked fixture context");
    fs::write(fixture.join("src/lib.rs"), "pub fn envctl_fixture() {}\n")
        .expect("write fixture source");

    let mut json_rows = None;
    for format in ["json", "nuon", "csv"] {
        let output = Command::new(env!("CARGO_BIN_EXE_codedb"))
            .args(["export", "envctl", "--repo-path"])
            .arg(&fixture)
            .args(["--format", format])
            .output()
            .expect("run packaged CodeDB envctl export");
        assert!(
            output.status.success(),
            "envctl {format} export failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            !output.stdout.is_empty(),
            "envctl {format} export must produce rows"
        );
        if format == "json" {
            json_rows = Some(
                serde_json::from_slice::<Vec<BTreeMap<String, String>>>(&output.stdout)
                    .expect("parse envctl JSON rows"),
            );
        }
    }

    let rows = json_rows.expect("JSON export is captured");
    let checksums = rows
        .iter()
        .filter(|row| {
            row.get("table")
                .is_some_and(|table| table == "codedb_table_checksums")
        })
        .map(|row| (row["source_table"].clone(), row["sha256"].clone()))
        .collect::<BTreeMap<_, _>>();

    assert!(
        checksums.contains_key("filesystem_entries")
            && checksums.contains_key("codedb_source_root_hashes"),
        "envctl must export checksums for each materialization source table: {checksums:?}"
    );
    for row in rows.iter().filter(|row| {
        row.get("table")
            .is_some_and(|table| table == "codedb_materialization_targets")
    }) {
        let source_table = &row["source_table"];
        assert_eq!(
            row.get("source_table_checksum"),
            checksums.get(source_table),
            "materialization row must bind its declared source table checksum: {row:?}"
        );
    }
    assert!(rows.iter().all(|row| {
        row.get("backend_internal_access")
            .is_none_or(|access| access == "forbidden")
    }));

    fs::remove_dir_all(root).expect("remove integration-test root");
}

#[test]
fn runner_proof_manifest_is_exportable_for_noninteractive_runners() {
    let root = temp_root();
    let fixture = root.join("fixture");
    fs::create_dir_all(fixture.join("src")).expect("create fixture source");
    fs::write(
        fixture.join("Cargo.toml"),
        "[package]\nname = \"runner_proof_fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write fixture manifest");
    fs::write(
        fixture.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"runner_proof_fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write locked fixture context");
    fs::write(
        fixture.join("src/lib.rs"),
        "pub fn runner_proof_fixture() {}\n",
    )
    .expect("write fixture source");

    for format in ["json", "nuon", "csv"] {
        let output = Command::new(env!("CARGO_BIN_EXE_codedb"))
            .args([
                "export",
                "runner_proof_manifest",
                "--repo-id",
                "runner-proof-fixture",
                "--repo-path",
            ])
            .arg(&fixture)
            .args(["--store", ".codedb/runner-proof.redb", "--format", format])
            .output()
            .expect("run runner proof export");
        assert!(
            output.status.success(),
            "runner proof {format} export failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            !output.stdout.is_empty(),
            "runner proof {format} export must produce rows"
        );

        if format == "json" {
            let rows = serde_json::from_slice::<Vec<BTreeMap<String, String>>>(&output.stdout)
                .expect("parse runner proof JSON rows");
            assert!(rows.iter().all(|row| {
                row.get("table") == Some(&"runner_proof_manifest".to_string())
                    && row.get("release_without_provenance") == Some(&"forbidden".to_string())
                    && row.contains_key("gate_id")
                    && row.contains_key("status")
                    && row.contains_key("evidence")
                    && row.contains_key("raw_log_path")
            }));
            assert!(rows.iter().any(|row| {
                row.get("gate_id") == Some(&"runner_manifest".to_string())
                    && row.get("status") == Some(&"satisfied".to_string())
                    && row.get("repo_id") == Some(&"runner-proof-fixture".to_string())
            }));
            assert!(rows.iter().any(|row| {
                row.get("gate_id") == Some(&"release_readiness".to_string())
                    && row.get("status") == Some(&"pending".to_string())
            }));
        }
    }

    fs::remove_dir_all(root).expect("remove integration-test root");
}
