# Generated by CodeDB. Do not edit.
# Version: @CODEDB_VERSION@
# Purpose: lightweight Yazelix Nushell extern bridge for the CodeDB CLI.

extern "codedb" [
    ...args: string
]

extern "nu_plugin_codedb" []
